/** English locale strings for fork-sync HTML email report. */
export const en = {
  lang: "en",
  title: "Fork Sync Report",
  dryRunSuffix: " · DRY RUN",
  scannedUnit: (n) => `${n} fork${n === 1 ? "" : "s"} scanned`,
  stats: {
    scanned: "Scanned",
    merged: "Merged",
    conflicts: "Conflicts",
    upstreamCreated: "Upstream+",
    upToDate: "Up to date",
    errorsSkipped: "Errors / Skipped",
  },
  sections: {
    upstream: "A · Upstream created",
    conflicts: "B · Conflicts / PR open",
    merged: "C · Merged",
    errors: "D · Errors / skipped",
    runs: "E · Last 24h workflow runs",
  },
  columns: {
    repository: "Repository",
    parent: "Parent",
    forkParentDefault: "Fork / Parent default",
    branches: "Branches",
    statuses: "Statuses",
    sha: "SHA",
    note: "Note",
    pr: "PR",
    compare: "Compare",
    whenUtc: "When (UTC)",
    title: "Title",
    status: "Status",
    conclusion: "Conclusion",
    link: "Link",
  },
  allUpToDate: (n) => `All ${n} fork(s) are up to date. No action needed.`,
  noRuns:
    "No workflow runs found in the last 24 hours (or unavailable outside Actions).",
  footer: "Generated by chloemlla fork-sync.",
  currentRun: "Current workflow run",
  subject: {
    failed: (day, errors, n) =>
      `[Fork Sync] FAILED — ${day} (${errors} errors, ${n} forks)`,
    allClean: (day, n) => `[Fork Sync] ${day} — all up to date (${n} forks)`,
    summary: (day, merged, conflicts, errors) =>
      `[Fork Sync] ${day} — ${merged} merged, ${conflicts} conflicts, ${errors} errors`,
  },
};
